application: klusty8
version: 1a-2c-1h
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: .*
  script: klusty8.app


libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: latest